name: Deploy to GitHub Pages Staging And Prod
on: 
    workflow_dispatch:
    push:
        branches:
        - master
jobs:
  build-and-deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: build/
 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          token: ${{ secrets.TOKEN }}
          repository-name: kaverma/actions-demo-staging
          
  build-and-deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: prod
    needs: build-and-deploy-staging
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
 
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          token: ${{ secrets.TOKEN }}
          repository-name: kaverma/actions-demo
